### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by fid3n** [Akebi-Group/Akebi-GC#87]
usin' lastest offic. release

```
upload_crash release upload:350946
__main__ Exception('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 665, in urlopen
  File "urllib3\connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 416, in _make_request
  File "http\client.py", line 1347, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 719, in urlopen
  File "urllib3\util\retry.py", line 400, in increment
  File "urllib3\packages\six.py", line 734, in reraise
  File "urllib3\connectionpool.py", line 665, in urlopen
  File "urllib3\connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 416, in _make_request
  File "http\client.py", line 1347, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upload_crash.py", line 86, in <module>
  File "upload_crash.py", line 80, in upload_crash
  File "requests\api.py", line 119, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
```

**Comment by Taiga74164** [comment]
upload crash doesn't help us figure out the crash. please tell us what you did and what features you had on

**Comment by fid3n** [comment]
just first inject
and btw, on what button is gui

**Comment by fid3n** [comment]
i'm 2 lazzzy to open sc

**Comment by Taiga74164** [comment]
> just first inject and btw, on what button is gui

F1

**Comment by fid3n** [comment]
why not insert or del

**Comment by fid3n** [comment]
f1 is bound to genshins book

**Comment by fid3n** [comment]
do u have genshin xyz sc?

**Comment by fid3n** [comment]
![image](https://user-images.githubusercontent.com/102911531/172267836-bbcbab2a-d3ef-4ad8-bfb3-9bbbea453c65.png)

And what's this
